# Generated by Django 5.1.1 on 2024-09-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_company_remove_position_organization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individual",
            old_name="possition",
            new_name="position",
        ),
    ]
